### PR TITLE
Support Java8 and fix WAR file generation

### PR DESCRIPTION
**Pull request by ygrignon-sfdc**

### CODE REVIEW

**Comment by ygrignon-sfdc** [comment]
I fixed the WAR file generation so you can now launch it using jetty:run-war or use it in any app server. I also fixed test failures related to Java8. One file I was not able to fix so I marked as Ignore until somebody that understands the right behavior can take a look.

**Comment by pdragosh** [comment]
I'm getting this issue now when I run the PAP Admin:

Caused by: java.lang.NoClassDefFoundError: com/google/gwt/thirdparty/guava/common/base/Splitter

Not sure if upgrading the Vaadin version caused this and if we are missing a dependency now. Any ideas?

I'm trying to upgrade all the projects to run with jetty:run-war and also deploy the missing jar's to maven repository.

**Comment by ygrignon-sfdc** [comment]
Hi Pam,

Something like this should work:

     ...

     <properties
         ...
         <jetty.version>9.0.0.v20130308</jetty.version>
     </properties>

     ...

      
      <plugin>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-maven-plugin</artifactId>
        <version>${jetty.version}</version>
        <dependencies>
          <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-io</artifactId>
            <version>${jettyVersion}</version>
          </dependency>
          <dependency>
            <groupId>org.w3c.css</groupId>
            <artifactId>sac</artifactId>
            <version>1.3</version>
          </dependency>
          <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-shared-deps</artifactId>
            <version>1.0.3</version>
          </dependency>
          <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-themes</artifactId>
            <version>${vaadin.version}</version>
          </dependency>
          <dependency>
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>eclipselink</artifactId>
            <version>2.5.2</version>
          </dependency>
        </dependencies>
        <configuration>
          <httpConnector>
            <port>8090</port>
            <idleTimeout>60000</idleTimeout>
          </httpConnector>
          <war>${project.build.directory}/${project.name
}-${project.version}.war</war>
          <webApp>
            <contextPath>/</contextPath>
          </webApp>
        </configuration>
      </plugin>



Thanks!

Yanik

**Comment by ygrignon-sfdc** [comment]
With the above, it can't find the property file. Copying it in the project directory works, but then you run into an h2 path error. Some work is still needed there to get it working.

Here I'm using another maven project that consumes the war produced by the XACML-PAP-ADMIN project and provides its own xacml.admin.properties.

**Comment by pdragosh** [comment]
Thanks, the dependencies helped. I'm moving the properties file back to the root directory. Working on the H2 problem now. Never saw that when first developing it, much changes over a couple of years.

**Comment by ygrignon-sfdc** [comment]
My own xacml.admin.properties uses

javax.persistence.jdbc.url=jdbc:h2:file:./sql/xacml;MODE=MySQL


Thanks!

Yanik

**Pull request merged**
